server:
  port: 8100

spring:
  application:
    name: owner


zuul:
  routes:
    customer_service:
      url: http://localhost:8081
    rooms_service:
      url: http://localhost:9002
    employee_service:
      url: http://localhost:9003
    payment_service:
        url: http://localhost:9999
    manager:
        url: http://localhost:9004
    receptionist:
        url: http://localhost:8004





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost